### ISSUE TITLE
Unable to use individual options

### ISSUE THREAD

**Issue by fbid** [ClintH/gtbg#2]
Hi,

I need to use some individual options in order to process my samples.

This is the command I run:
`gtbg ot --samples "./chains/src/process" --outputPath "./output/" --autoGain=true --removeStereo=true`

or

`gtbg ot --samples "./chains/src/process" --outputPath "./output/" --autoGain="true" --removeStereo="true"`

In both cases the files are being successfully processed, but they are still stereo and they are not normalized. 

What am I doing wrong? Is the options not supposed to be used like I am using them?

Thank you

**Comment by ClintH** [comment]
Hi there,

Do you have the latest version installed? 0.2.0 fixed some bugs related to stereo processing.

**Comment by fbid** [comment]
Hi, thank you for your reply. 

Just to be sure I had the latest version installed I run `npm install -g gtbg` again, and the installation seems to be fine.

`/usr/local/bin/gtbg -> /usr/local/lib/node_modules/gtbg/app.js`
`/usr/local/lib`
`└─┬ gtbg@0.2.0`
`├── async@0.9.0`
`├─┬ chalk@1.1.1`
`│ ... and so on``

but after entering `gtbg` as a shell command, now this is what I get.

`env: node\r: No such file or directory`

I'm on Mac OS X 10.10.5

**Comment by ClintH** [comment]
Sorry about that, messed up the line endings by editing on a PC. If you run "npm update -g gtbg" (prefixed with 'sudo' if necessary) you should get 0.2.1 which I've tested to work on my Mac. Thanks for reporting!

**Comment by fbid** [comment]
I'm glad I was able to help. Now it's working good.
